# site_name: My Docs
extra_css:
  - assets/custom.css

site_name: RobiS Robot Manual
theme:
  name: material

theme:
  name: readthedocs


nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - Remote Control: getting-started/remote-control.md
      - Remote Login: getting-started/remote-login.md
  - ROS Navigation:
      - Driver Startup: navigation/ros-startup.md
      - 2D LiDAR Mapping: navigation/lidar-mapping.md
      - 2D Navigation: navigation/lidar-navigation.md
      - Cartographer Navigation: navigation/cartographer.md
      - Depth Camera: navigation/depth-camera.md
  - Autoware:
      - 3D SLAM & Navigation: autoware/3d-navigation.md

  - FAQ: faq.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - footnotes
  - attr_list
